let welcome ="hello";
let name ="tayyab";
let age ="your age is";
let him  ="4";
let greeting =" you are cute";
console.log(welcome);
console.log(name);
console.log(age);
console.log(him);
console.log(greeting);
document.querySelector(".sub").innerHTML=("hello tayyab  your age is 4 you are cute");